package View;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField; // Importar JTextField explicitamente
import javax.swing.JLabel;    // Importar JLabel explicitamente
import javax.swing.JButton;   // Importar JButton explicitamente
import javax.swing.JMenuBar;  // Importar JMenuBar explicitamente
import javax.swing.JMenu;     // Importar JMenu explicitamente
import javax.swing.JFrame;    // Importar JFrame explicitamente
import java.awt.event.ActionEvent; // Importar ActionEvent explicitamente
import java.awt.event.ActionListener; // Importar ActionListener explicitamente
import java.util.logging.Level; // Importar Level para o logger

/**
 *
 * @author pedro
 */
public class LoginFuncionario extends JFrame { // extends JFrame

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFuncionario.class.getName());

    /**
     * Creates new form LoginFuncionario
     */
    public LoginFuncionario() {
        initComponents();
        setTitle("Login de Funcionário - MyCommerce"); // Adicionei o título da janela
        setLocationRelativeTo(null); // Centraliza a janela na tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // Declaração e inicialização dos componentes Swing
        jTextFieldLogin = new JTextField();
        jPasswordFieldSenha = new JPasswordField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jButton1 = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu(); // Menu Arquivo
        jMenu2 = new JMenu(); // Menu Sobre

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("LOGIN");

        jLabel2.setText("SENHA");

        jButton1.setText("CONFIRMAR");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt); // Chama o método de ação para o botão CONFIRMAR
            }
        });

        // Configuração do Menu "Arquivo"
        jMenu1.setText("Arquivo");
        javax.swing.JMenuItem sairItem = new javax.swing.JMenuItem("Sair");
        sairItem.addActionListener(e -> System.exit(0)); // Ação para sair da aplicação
        jMenu1.add(sairItem);
        jMenuBar1.add(jMenu1);

        // Configuração do Menu "Sobre"
        jMenu2.setText("Sobre");
        javax.swing.JMenuItem sobreItem = new javax.swing.JMenuItem("Sobre");
        sobreItem.addActionListener(e -> {
            new Sobre().setVisible(true); // Abre a tela "Sobre"
        });
        jMenu2.add(sobreItem);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        // Layout (ajustado para usar JTextField e JPasswordField)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLogin, 150, 150, Short.MAX_VALUE) // Ajustado largura
                            .addComponent(jPasswordFieldSenha))) // Campo de senha
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) // Use BASELINE para JTextField
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) // Use BASELINE para JPasswordField
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>

    /**
     * Este método é chamado quando o botão 'CONFIRMAR' (jButton1) é clicado.
     * É aqui que você adicionará a lógica de verificação de login e navegação para a próxima tela.
     * @param evt O evento de ação gerado pelo clique do botão.
     */
    private void jButton1ActionPerformed(ActionEvent evt) {
        // Obter o texto do campo de login
        String login = jTextFieldLogin.getText();

        // Obter a senha do JPasswordField de forma segura
        String senha = new String(jPasswordFieldSenha.getPassword());

        // Lógica de Validação de Login
        if (login.equals("admin") && senha.equals("123")) {
            JOptionPane.showMessageDialog(this, "Login bem-sucedido!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            // Abrir a Tela Inicial
            new TelaInicial().setVisible(true); // Garanta que a classe TelaInicial esteja no mesmo pacote View
            // Fechar a tela de Login
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Login ou senha incorretos.", "Erro de Login", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold> 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFuncionario().setVisible(true));
    }

    // Variables declaration - do not modify
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JTextField jTextFieldLogin;
    private JPasswordField jPasswordFieldSenha;
    // End of variables declaration
}